--
-- @author Leboc Philippe, Hugo Sereni
--
-- CREATE ALL TABLES
CREATE TABLE IF NOT EXISTS groups (
name VARCHAR(16) NOT NULL,
PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS students (
id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
last_name VARCHAR(16) NOT NULL,
first_name VARCHAR(16) NOT NULL,
password VARCHAR(16) NOT NULL,
birth_date DATE NOT NULL,
group_name VARCHAR(16) NOT NULL REFERENCES groups(name)
);

CREATE TABLE IF NOT EXISTS teachers (
id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
last_name VARCHAR(16) NOT NULL,
first_name VARCHAR(16) NOT NULL,
password VARCHAR(16) NOT NULL,
birth_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS secretaries (
id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
last_name VARCHAR(16) NOT NULL,
first_name VARCHAR(16) NOT NULL,
password VARCHAR(16) NOT NULL,
birth_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS intervals (
id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
name VARCHAR(16) NOT NULL,
start_hour INTEGER(1) NOT NULL,
end_hour INTEGER(1) NOT NULL,
day INTEGER(1) NOT NULL,
teacher_id INTEGER NOT NULL REFERENCES teachers(id),
group_name INTEGER NOT NULL REFERENCES groups(name)
);